### PR TITLE
initial styling and collecting data from spreadsheet

### PR DESCRIPTION
**Pull request by pcsandford**
@mmeiers please review. I have added the initial styling for the theme including the embedded svg for basic animation (I plan to tidy up the original svg and run through a code minimiser for the final version). Thanks!

@stulees I have set up the file structure to match earlier themes and have based the JS on that which Donna used for the donor wall reworking. I have not yet added the JS to display the event slides in order, this will be the next PR. Thanks!

### CODE REVIEW

**Comment by stulees** [comment]
@pcsandford I'm seeing commented out code in `index.html` and `style.css`, is this intended to be uncommented in the future?

**Comment by pcsandford** [comment]
@stulees sorry, yes, all commented out code will be removed in the next PR. Thanks!

**Comment by mmeiers** [comment]
@pcsandford :+1: Looks good. I notice most people embed the svg xml into the html as you did instead of load it as an external svg file. Does it actually load faster embedded?

**Comment by pcsandford** [comment]
@mmeiers I think embedding is the only way to access specific paths if you are using CSS to control animations (you used to be able to use <animation> tags directly in the svg but this is deprecated sadly). I didn't notice any real difference in load time as it is fairly small, but I think that this way would be faster as it does not have to fetch an external file. I know there is a way to 'inject' svg xml into the html so I will check this out to see if it is neater in the end. Thanks!

**Comment by stulees** [comment]
@pcsandford @mmeiers Ionic has an open source SVG injector, you can add it as a bower dependency and it looks pretty easy to use. - https://github.com/iconic/SVGInjector

**Comment by pcsandford** [comment]
@stulees @mmeiers thanks! I was looking at that yesterday as well as https://www.npmjs.com/package/svg-inject I will definitely try it out.

**Comment by mmeiers** [comment]
@pcsandford Your svg is rather small so I think its fine but ya the injector is worth looking into. Some of the svgs ive worked with have been massive!

**Comment by pcsandford** [comment]
@mmeiers totally! I would be good to have a standard tool going forward for sure. Thanks!

**Pull request merged**
